[package]
name = "maia"
version = "0.1.0"
edition = "2024"


[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
clap = { version = "4.5.40", features = ["derive"] }


[dependencies]
serde.workspace = true
serde_json.workspace = true
clap.workspace = true


[workspace]
members = ["todo", "daemon"]
