[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
tokio = { version = "1.46.1", features = ["macros", "rt", "net", "io-util"] }
base64 = "0.22.1"
notify-rust = "4.5.0"
ai = { path = "../ai" }
todo = { path = "../todo" }
finance = { path = "../finance" }
food = { path = "../food" }
knowledge = { path = "../knowledge" }
